### ISSUE TITLE
Compatibility with Greasemonkey 4

### ISSUE THREAD

**Issue by killje** [YePpHa/maia-yt#59]
Because Greasemonkey are updating to be compatible with the new Browser Extension API, they have made a backwards incompatible change.

URL's to there blog:
http://www.greasespot.net/2017/09/greasemonkey-4-announcement.html
http://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

TL;DR:
- The new greasemonkey is going to use `GM.` variable instead of the old `GM_` (both in grand and code)
- `GM.` returns a promise instead of a value.

Version 4 is still in alpha and not finalized yet, but i thought a heads up would be in place here

**Comment by killje** [comment]
Alpha build available through:
https://github.com/greasemonkey/greasemonkey/releases

**Comment by YePpHa** [comment]
Interesting. I will need to do a few changes for how I handle saving and loading settings. 

The main part that I need to revisit for this to work correctly is to probably make the synchronous parts of the modules accept asynchronous responses. This needs to be handled in the core code where I intercept the `yt.player.Application.create` method. Moreover that method is a synchronous method and things might break if the player is not created immediately after the method is called.

It might be possible to not use asynchronous code in the modules and instead cache the settings. I will need to experiment with this before I can decide on which way to go.

**Comment by Yonezpt** [comment]
@YePpHa So far the only one that needs to be asynchronous (or at least behaves as such) is the *getValue method and the timing is not noticeable while trying to do the first interceptions. I've made a GM 3.* / 4 make-shift poly-fill here if it helps: 

https://github.com/ParticleCore/Iridium/blob/40545039a9b29f9477a6f4fe24e3588efc2a8c8b/src/userscript/Iridium.user.js#L5602-L5630

and the new use for *.getValue

https://github.com/ParticleCore/Iridium/blob/40545039a9b29f9477a6f4fe24e3588efc2a8c8b/src/userscript/Iridium.user.js#L5573-L5581

Decided not to make use of `await` since it required making the entire script `async` from what I gathered.

**Comment by YePpHa** [comment]
@Yonezpt I've decided to try out making Maia asynchronous as it would be the most ideal thing. I might also just scrap making it asynchronous and preload all settings and let the `handlePlayerCreate` method wait for it to preload before starting. It really depends on if I experience some show stopper due to async interacting with a sync environment.

I've been experimenting with making Maia asynchronous and it works for the most part. I haven't been able to change everything as the API calls to the YouTube player are all synchronous. If I want to intercept them I can't do that asynchronous except if I don't need to return a value. That means some of the API calls I can intercept asynchronous and some I can't. The good news is that the current API calls I intercept can be asynchronous.

The preventing of player events are not working in the async environment due to the current event system in Maia being synchronous as it's based on the DOM events.

Branch: https://github.com/YePpHa/maia-yt/tree/async

Test build with support for GreaseMonkey v4:
[maia.user.js.zip](https://github.com/YePpHa/maia-yt/files/1503329/maia.user.js.zip)

**Comment by YePpHa** [comment]
Okay, I've done some more tests. I've decided to not make Maia asynchronous as it introduces unneeded complexity in translating between synchronous and asynchronous environments.

What I will do instead is to preload the storage for each module and prevent `yt.player.Application.create` from starting before it has completed the preload.

**Comment by YePpHa** [comment]
I've implemented GM4 in [https://github.com/YePpHa/maia-yt/releases/tag/v0.1-alpha.9](v0.1.9).
