### ISSUE TITLE
Doesn't work on embedded videos?

### ISSUE THREAD

**Issue by TroudhuK** [YePpHa/maia-yt#63]
Is it supposed to work for embedded videos, like YTC, or not yet?

If I ask for that, of course, it's because it doesn't work for me but I have a lot of other extensions, protections etc. so maybe it's a specific problem to me.

**Comment by YePpHa** [comment]
Seems like I'm calling some player methods that are not available for the embedded videos. I will replace those with method that are available for the embedded videos. Moreover, I also found out that the quality module didn't work due to some timing issue.

I might want to separate some settings to allow different settings for embedded, detail page and profile page videos. However, I wont be doing that yet.

The following modules should work in the next alpha version:
- adblock
- quality
- player element focus

**Comment by YePpHa** [comment]
Version that fixes this https://github.com/YePpHa/maia-yt/releases/tag/v0.1-alpha.6

**Comment by YePpHa** [comment]
Ahh yeah, the `@noframes` metadata. I could remove it, but GreaseMonkey in the future will always have `@noframes` turned on.
